Fix make_http_request
USEPA/esupy pull request #20
Opened 2021-11-19 20:26 UTC by matthewlchambers

Improved control flow and robustness of `make_http_request`, and renamed it as `make_url_request` to reflect the fact that it can make FTP requests as well. I also provided `make_http_request` as an alias for `make_url_request`, with a logged deprecation warning, since `stewi` imports and uses `make_http_request` from this package(I've also submitted a PR on `stewi` to change the name).

2021-11-19 20:36 UTC, bl-young commented
Will this align with https://github.com/USEPA/flowsa/pull/144, meaning, should flowsa just use the esupy function here?

I haven't yet looked closely but its possible that the original flowsa function existed before esupy so we can probably consolidate there now.

2021-11-24 15:42 UTC, matthewlchambers commented
> Will this align with [USEPA/flowsa#144](https://github.com/USEPA/flowsa/pull/144), meaning, should flowsa just use the esupy function here?
> 
> I haven't yet looked closely but its possible that the original flowsa function existed before esupy so we can probably consolidate there now.

The flowsa function includes a couple of lines to deal with websites that require cookies. It would be easy to add those lines to the `esupy` function and then have flowsa use the `esupy` function. Would you like me to make that change and submit a new pull request?

2021-11-30 12:55 UTC, WesIngwersen commented
> > Will this align with [USEPA/flowsa#144](https://github.com/USEPA/flowsa/pull/144), meaning, should flowsa just use the esupy function here?
> > I haven't yet looked closely but its possible that the original flowsa function existed before esupy so we can probably consolidate there now.
> 
> The flowsa function includes a couple of lines to deal with websites that require cookies. It would be easy to add those lines to the `esupy` function and then have flowsa use the `esupy` function. Would you like me to make that change and submit a new pull request?

@catherinebirney please weigh in on this

2021-12-01 16:36 UTC, bl-young commented
@matthewlchambers yes I think you can go ahead and make that change here, add that set_cookies parameter the same as used in flowsa than we can drop that function in flowsa and use this one instead

2021-12-02 20:25 UTC, bl-young requested changes
see comment above

2021-12-03 14:02 UTC, matthewlchambers commented
Ok, I've added the cookie handling code to the esupy function. Before removing the flowsa.common function, do you want me to add the new JobLib related code (that just recently got added to the flowsa.common function as decoration) to the esupy function as well?

2021-12-03 14:06 UTC, matthewlchambers commented
Actually, I was wondering about that JobLib caching anyway; it doesn't seem like we should be calling the exact same url very often. Unless this happens in connection with a data source I'm not familiar with yet?

2021-12-03 14:10 UTC, bl-young commented
> Before removing the flowsa.common function, do you want me to add the new JobLib related code (that just recently got added to the flowsa.common function as decoration) to the esupy function as well?

I was just looking to see if we can cache a function call from another package, that is, maintain the JobLib memory caching only for flowsa. I'm not sure we want to always cache these across the tool ecosystem. I suppose in flowsa we could create a pass through function that has the cache.

2021-12-03 14:57 UTC, matthewlchambers commented
Can you point me to the use case that prompted implementing caching? Also, I wonder if we should be using a caching method specifically intended for caching http requests, such as that found in the package requests-cache, rather than JobLib.

2021-12-03 14:58 UTC, matthewlchambers commented
In any case, we can certainly implement a pass-through function in flowsa that caches using JobLib if that's desired.

2021-12-03 15:16 UTC, bl-young commented
Let's discuss further when @catherinebirney returns next week. She was the one who implemented the caching so I don't want to speak for her. If i recall it was suggested by one of the package reviewers

2021-12-06 15:51 UTC, catherinebirney commented
I agree with dropping make_url_request() from flowsa and calling on the esupy function. I've thought about the JobLib caching as well - it is helpful for developers for testing purposes, but outside of testing, JobLib is not overly useful because as @matthewlchambers points out, the same urls are not called often. I'm open to dropping JobLib from the repo and I'll continue to use caching locally

2021-12-06 16:59 UTC, bl-young commented
merging in to esupy, @catherinebirney @matthewlchambers i'll let you all decide on what you'd like to do about the caching in flowsa and what other updates are needed there to transition to using this function.

2021-12-06 16:59 UTC, merged

2021-12-06 19:03 UTC, matthewlchambers commented
@catherinebirney , I'll go ahead then and submit a pull request removing the JobLib caching and replacing the `flowsa.common` function with the `esupy` function throughout the flowsa package.